Algoritmo "Aula 2 exercicio 2"
// Disciplina   : BASES DE CIÊNCIA DA COMPUTAÇÃO I - COMPUTAÇÃO 
// Professor   : FLÁVIO JOSÉ FERRO BARROS

Var
Valor1, Valor2: inteiro


Inicio
escreva ("Insira um valor:")
leia (Valor1)
escreva ("Insira outro valor:")
leia (Valor2)
se Valor1 > Valor2 entao
 escreva (Valor1-Valor2)
senao Valor1 < Valor2
 escreva (Valor2-Valor1)
fimse

Fimalgoritmo
