Algoritmo "Aula 2 exercicio 3"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 

Var
Nota1, Nota2, Nota3: inteiro

Inicio
escreva ("Insira a primeira nota:")
leia (Nota1)
escreva ("Insira a segunda nota:")
leia (Nota2)
escreva ("Insira a terceira nota:")
leia (Nota3)
se (Nota1+Nota2+Nota3)/3 >= 70 entao
 escreva ("Você está aprovado")
senao
escreva ("Você está reprovad")
fimse


Fimalgoritmo